### 제곱합<br>
<br>
데이터의 분산(variance)이나 표준 편차(standard deviation)을 구하는 경우에는 각각의 데이터를 제곱한 뒤 이 값을 모두 더한 값 즉 제곱합(sum of squares)을 계산해야 한다.<br>
이 경우에도 벡터의 곱을 사용하여 $x^{T}x$로 쓸 수 있다.

$$
x^{T}x=
\begin{bmatrix}
x_1 & x_2 & \ldots & x_N
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
\vdots \\
x_N
\end{bmatrix}
=
\sum_{i=1}^N x_i^2
$$

### 행렬과 행렬의 곱셈 <br>
<br>
$A$ 행렬과 $B$ 행렬을 곱한 결과가 $C$ 행렬이 된다고 하자.<br>
$C$의 $i$번째 행, $j$번째 열의 원소<br> 
$C_{ij}$의 값은 <br>
* $A$ 행렬의 $i$번째 행 벡터 $a_i^T$와<br> 
* $B$ 행렬의 $j$번째 열 벡터 $b_j$의 곱이다.

$$
C = AB \rightarrow C_{ij} = a_i^T b_j
$$

이 정의가 성립하려면 행렬 $A$의 <span style="color:purple">열</span>의 수와 뒤의 행렬 $B$의 <span style="color:purple">행</span>의 수가 일치 해야만 한다.

$$
A \in R^{N \times \color{purple}{L}}, B \in R^{\color{purple}L \times M} \rightarrow AB \in R^{N \times M}
$$

다음은
$$
A \in R^{4 \times \color{purple}{3}}, B \in R^{\color{purple}3 \times 2} \rightarrow AB \in R^{4 \times 2}
$$

<br>
의 예)<br>
<br>
$$
\begin{bmatrix}
\color{red}a_{1,1} & \color{red}a_{1,2} & \color{red}a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3} \\
a_{4,1} & a_{4,2} & a_{4,3} \\
\end{bmatrix}
\begin{bmatrix}
\color{blue}b_{1,1} & b_{1,2} \\
\color{blue}b_{2,1} & b_{2,2} \\
\color{blue}b_{3,1} & b_{3,2} \\
\end{bmatrix}=
$$

$$
\begin{bmatrix}
\color{red}a_{1,1} \color{blue}b_{1,1} & + & \color{red}a_{1,2} \color{blue}b_{2,1} & + & \color{red}a_{1,3} \color{blue}b_{3,1} & \color{red}a_{1,1} b_{1,2} & + & \color{red}a_{1,2} b_{2,2} & + & \color{red}a_{1,3} b_{3,2} \\
a_{2,1} \color{blue}b_{1,1} & + & a_{2,2} \color{blue}b_{2,1} & + & a_{2,3} \color{blue}b_{3,1} &
a_{2,1} b_{1,2} & + & a_{2,2} b_{2,2} & + & a_{2,3} b_{3,2} \\
a_{3,1} \color{blue}b_{1,1} & + & a_{3,2} \color{blue}b_{2,1} & + & a_{3,3} \color{blue}b_{3,1} &
a_{3,1} b_{1,2} & + & a_{3,2} b_{2,2} & + & a_{3,3} b_{3,2}\\
a_{4,1} \color{blue}b_{1,1} & + & a_{4,2} \color{blue}b_{2,1} & + & a_{4,3} \color{blue}b_{3,1} &
a_{4,1} b_{1,2} & + & a_{4,2} b_{2,2} & + & a_{4,3} b_{3,2}\\
\end{bmatrix}
$$

$A$, $B$가
$$
A=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$$
<br>
$$
B=
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 \\
\end{bmatrix}
$$
일 때 Numpy로 내적 계산

In [12]:
import numpy as np

A = np.array([[1, 2, 3],\
              [4, 5, 6]])

B = np.array([[1, 2],\
              [3, 4],\
              [5, 6]])

C = np.dot(A, B)
C

array([[22, 28],
       [49, 64]])

인공 신경망은 내부적으로 다음과 같이 여러 개 선형 회귀 모형을 이용.<br>
이 구조는 행렬과 벡터의 곱으로 나타낼 수 있다.<br>
<br>
<img src ="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeaLW-a257rd1cAPzAuWayrM_HN10SqQKMHwqQaFVyoM7aCdzp">

위 그림을 행렬식으로 표현

$$
Y=
\begin{bmatrix}
W_1 & W_2 & W_3
\end{bmatrix}
\begin{bmatrix}
X_1 \\
X_2 \\
X_3 \\
\end{bmatrix}
$$
<br>
$$
\hat{y} = WX
$$

## 교환 법칙과 분배 법칙

$$
AB \neq BA\\
A(B + C) = AB + AC\\
(A+B)C = AC + BC
$$

NumPy로 위의 법칙이 성립하는지 확인
$$
A=
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}\\
B=
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}\\
C=
\begin{bmatrix}
9 & 8 \\
7 & 6
\end{bmatrix}
$$

In [3]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 8], [7, 6]])

In [6]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [8]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

분배법칙

In [10]:
np.dot(A, B + C)

array([[42, 42],
       [98, 98]])

In [15]:
np.dot(A, B) + np.dot(A , C)

array([[42, 42],
       [98, 98]])

In [16]:
np.dot(A+B, C)

array([[110,  96],
       [174, 152]])

In [18]:
np.dot(A, C) + np.dot(B, C)

array([[110,  96],
       [174, 152]])

전치 연산에서 (+, -)은 같은 법칙이 적용된다.
$$
(A+B)^T = A^T + B^T
$$

전치 연산에서 ($\times$, $\div$)은 분배 법칙되면서 연산의 **순서**가 바뀐다.

$$
(AB)^T = B^T A^T\\
(ABC)^T = C^T B^T A^T
$$

Numpy로 다시 확인

In [20]:
(A + B).T

array([[ 6, 10],
       [ 8, 12]])

In [22]:
A.T + B.T

array([[ 6, 10],
       [ 8, 12]])

In [24]:
(np.dot(A, B)).T

array([[19, 43],
       [22, 50]])

In [ ]:
B.T 