# 행렬의 성질

## 행렬의 부호

행렬은 여러개의 숫자로 이루어져 있기 떄문에 행렬 전체의 부호는 정의하기 힘들다. <br>
그러나 행렬에서도 **실수** 부호와 비슷한 특성이 있다.<br>

- 행렬의 <span style="color:red"> 양-정부호</span> (positive definite)특성이다.

영 벡터가 아닌 모든 벡터 $x$에 대해 다음 부등식이 성립하면 행렬 $A$가 **양-정부호(positive definite)** 이라고 한다.
$$
x^T Ax > 0
$$

만약 위 등식을 포함하면 **양-준정부호(positive semi-definite)**라고 한다.

$$
x^T Ax \ge 0
$$

예를 들어 단위 행렬($I$)은 양-정부호이다.<br> 
벡터 $x$는 영 벡터가 아니라는 점에 주의한다.

$$
x^T Ix =
\begin{bmatrix}
x_1 & x_2 & \ldots & x_N
\end{bmatrix}
\begin{bmatrix}
1 & 0 & \ldots & 0 \\
0 & 1 & \ldots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \ldots & 1 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_N
\end{bmatrix}
= x_1^2 + x_2^2 + x_3^2 + \ldots + x_N^2 > 0
$$

아래 행렬도 양-정부호이다.
$$
A =
\begin{bmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2 \\
\end{bmatrix}
$$

이는 다음처럼 **증명**할 수 있다.<br>
모든 벡터 $x^T = \begin{bmatrix}x_1 & x_2 & x_3 \end{bmatrix}$에 대해

$$
x^T A x =
\begin{bmatrix}
x_1 & x_2 & x_3
\end{bmatrix}
\begin{bmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}
$$

행렬 잘못된 곱셈
$$
=
\begin{bmatrix}2x_1 + -x_1 + 0 & -x_2 + 2x_2 + -x_2 & 0 + -x_3 + 2x_3\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}
$$

올바른 곱셈(내적)
$$
=
\begin{bmatrix}
2x_1 + (-x_2) + 0 & (-x_1) + 2x_2 +(-x_3) & 0 + (-x_2) + 2x_3
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
2x_1^2+(-x_1x_2) + 0 + (-x_1x_2) + 2x_2^2 + (-x_2x_3) + 0 + (-x_2x_3)+2x_3^2
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
2x_1^2+2(-x_1x_2)+2x_2^2+2(-x_2x_3)+2x_3^2
\end{bmatrix}
$$

[인수분해(factorization)](https://ko.wikipedia.org/wiki/%EC%9D%B8%EC%88%98%EB%B6%84%ED%95%B4)를 통해 식을 변환<br>
ex)

$$
a^{2}\pm 2ab+b^{2}=(a\pm b)^{2}
$$

$$
=
\begin{bmatrix}
x_1^2 + (-x_1 + x_2)^2 + (-x_2 + x_3)^2 + x_3^2
\end{bmatrix}
$$

위의 값은 제곱의 합으로 이루어 졌으므로 $x_1 = x_2 = x_3 = 0$인 경우를 제외하고 항상 0 보다 크다.

$$
x_1^2 + (-x_1 + x_2)^2 + (-x_2 + x_3)^2 + x_3^2 > 0
$$

연습 문제 1
다음 행렬을 양-정부호, 양-준정부호 혹은 아무것도 해당되지 않는지 판단하라.
$$
\begin{bmatrix}
1 & 1 \\
1 & 1 \\
\end{bmatrix}
$$

In [9]:
import numpy as np

A = np.array([[1, 1], [1, 1]])
x = np.array([1, 2])

In [10]:
# x^T A x
np.dot(np.dot(x.T, A), x) # 9 > 0

9

In [11]:
B = np.array([[1, 1], [1, 1]])
y = np.array([-1, -2])

In [12]:
np.dot(np.dot(y.T, B), y)

9

결과 값은 9 이므로 양-정부호이다.

## 행렬의 크기

행렬의 크기를 정의하는 것도 어렵다.<br>
하나의 행렬에 대해 하나의 실수를 대응하는 개념<br>
<br>
**놈(norm), 대각합(trace), 행렬식(determinant)**이란 연산은<br>
<br>
행렬의 크기와 비슷한 의미가 있다.

### 행렬 놈

행렬의 **놈(norm)**은 행렬 $A$에 대해 아래와 같이 정의 되는 숫자.<br>
보통 $\left\| A \right\|_L$로 표기한다.<br>
$L$은 1,2 또는 무한대($\infty$)이다.<br>
아래 식에서 $a_{ij}$는 행렬 $A$의 $i$번째 행, $j$번째 열의 원소이다.

$$
\left\| A \right\|_L = \left( \sum_{i=1}^M \sum_{j=1}^N \left|a_{ij}^L\right| \right)^{1/L} 
$$

$L=1$이면 L1놈, $L=2$이면 L2놈 이라고 부른다.<br>
이 중 $L=2$인 경우가 많이 쓰이므로 L값 표시가 없는 경우 $L=2$인 놈이라고 생각면 된다.<br>
L2놈은 [프로베니우스 놈(Frobenius norm)](https://ko.wikipedia.org/wiki/%ED%94%84%EB%A1%9C%EB%B2%A0%EB%8B%88%EC%9A%B0%EC%8A%A4_%EB%B0%A9%EB%B2%95) 이라고 불리며 $\left\|A\right\|_F$이라고 표기하기도 한다.

$$
\left\|A\right\| = \left\| A \right\|_F = \sqrt{\sum_{i=1}^M \sum_{j=1}^N a_{ij}^2}
$$

$A$에 대한 각각의 원소 값에 제곱하고 난 후 합한 뒤 루트 계산하는것.

놈은 모든 크기의 행렬에 대해서 정의 할 수 있으므로 벡터에 대해서도 정의 가능.<br>
벡터의 놈의 제곱은 그 벡터의 제곱합과 같다.

$$
\left\|x\right\|^2 = \sum_{i=1}^N x_i^2 = x^T x
$$

따라서 벡터의 제곱합을 최소화(가장 작게 만드는 것)하는 것은 놈을 최소화 하는 것과 같다.<br>
<br>
행렬과 벡터의 놈은 항상 0과 같거나 0보다 큰 값을 가진다.<br>
Numpy에서는 linalg서브패키지의 <span style="color:red">norm</span>으로 놈을 계산.

In [4]:
import numpy as np
# np.arange(x) 는 0부터 x-1까지의 값을 말한다. , -4부터 시작
A = (np.arange(9) - 4 ).reshape((3,3))
B = (np.arange(9).reshape((3,3)))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [5]:
np.linalg.norm(A)

7.745966692414834

Numpy에서 행렬 놈2 증명해보기

In [10]:
import math

# 원소값
a = [-4, -3, -2, -1, 1, 2, 3, 4]
a_pow_box = 0

# 제곱
for i in a:
    a_pow = math.pow(i, 2)
    a_pow_box = a_pow_box + a_pow
    
# 루트
a_pow_sqrt = math.sqrt(a_pow_box)
print(a_pow_sqrt)

7.745966692414834


In [7]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.linalg.norm(B)

14.282856857085701

연습 문제 2<br>
행렬 $A(A \in R^{N \times M})$의 놈의 제곱 $\left\| A \right\|^2$이 그 행렬을 이루는 행 벡터$r_i$의 놈의 제곱의 합 또는 열 벡터 $c_i$의 놈의 제곱의 합과 같음을 증명하라.

$$
\left\| A \right\|^2 = \sum_{i=1}^N \left\| r_i \right\|^2 = \sum_{j=1}^M \left\| c_j \right\|^2
$$

### 대각합
**대각합(trace)**은 정방 행렬에 대해서만 정의.<br>
대각합은 대각의 원소들 합으로 계산된다.

$$
tr(A) = a_{11} + a_{22} + \ldots + a_{NN} = \sum_{i=1}^N a_{ii}
$$

대각합은 절대값이나 제곱을 하지 않기 때문에 놈과는 달리 0이나 음수가 가능.<br>
아래는 대각합의 성질<br>
아래 식 c는 scala이고, A,B,C는 matrix

$$
tr(cA) = c \times tr(A)
$$$$
tr(A^T) = tr(A)
$$$$
tr(A+B) = tr(A) + tr(B)
$$$$
tr(AB) = tr(BA)
$$$$
tr(ABC) = tr(BCA) = tr(CAB)
$$

특히 마지막 두식은 **트레이스 트릭(trace trick)** 이라고 하며 [이차 형식(quadratic form)](https://m.blog.naver.com/PostView.nhn?blogId=hextrial&logNo=220040851284&proxyReferer=https%3A%2F%2Fwww.google.co.kr%2F)의 [미분](https://namu.wiki/w/%EB%AF%B8%EB%B6%84)을 구하는데 유용하게 사용된다.

A, B ,C가 모두 정방행렬일 필요는 없고 대각합을 구하는 행렬이 정방행렬이면 된다.<br>
이차 형식의 트레이트 트릭<br>
ex)

$$
x^TAx = tr(x^TAx) = tr(Axx^T) = tr(xx^T A)
$$

이차 형식은 <span style="color:red">스칼라값</span>이 기 때문에 대각합을 취해도 원래의 값과 같다.<br>
Numpy에서 linalg 서브패키지의 <span style="color:red">trace</span> 명령으로 trace를 계산.

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
np.trace(np.eye(3))

3.0

연습 문제3<br>
x,A가 각각 크기가 2인 벡터, 크기가 2$\times$2 인 정방 행렬일 때 이차 형식의 트레이스 트릭이 성립합을 보인다.

In [1]:
import numpy as np

x = np.array([1, 2])
A = np.array([[3, 4], [5, 6]])
A

array([[3, 4],
       [5, 6]])

In [2]:
np.trace(A)

9

$x^Tx$   $tr(A)$

In [16]:
np.dot(x.T, np.dot(x, np.trace(A)))

45

$x^TAx$

In [12]:
np.dot(np.dot(x.T, A), x)

45

$Axx^T$

In [10]:
np.dot(np.dot(A,x), x.T)

45

### 행렬식
정방 행렬 $A$의 행렬식(determinant)은 $det(A)$라는 기호로 또는 $\left| A \right|$라는 기호로 표기

행렬식은 다음처럼 코팩터 전개(cofactor expansion)라고 불리는 재귀적인 방법으로 정의 된다.

$$
def(A) = \sum_{i=1}^N \left\{ (-1)^{i+j_0}M_{i,j_0} \right\} a_{i,j_0} = \sum_{j=1}^N \left\{ (-1)^{i_0 + j} M_{i_0, j} \right\} a_{i_0, j}
$$

이 식에서 $a_{i,j}$는 $A$의 $i$행, $j$열 원소이다.<br>
즉, 행렬에서 임의 행 $i_0$ 하나를 선택하거나 임의의 열 $j_0$ 하나를 선택한 다음 이 값에 가중치$(-1)^{i+j_0} M_{i,j_0}$ 또는 $(-1)^{i_0+j} M_{i_0,j}$를 곱하여 더한것.

$$
A=
\begin{bmatrix}
a_{i_1, j_1} & a_{i_1, j_2} & a_{i_1, j_3} \\
a_{i_2, j_1} & a_{i_2, j_2} & a_{i_2, j_3} \\
a_{i_3, j_1} & a_{i_3, j_2} & a_{i_3, j_3} \\
\end{bmatrix}
$$

가중치로 사용된 $M_{i,j}$는 마이너(minor, 소행렬식)라고 하며 정방 행렬 $A$에서 $i$행과 $j$열을 지워서 얻어진 (원래의 행렬보다 크기가 1만큼 작은) 행렬의 행렬식이다.

$$
M_{1,1} =
\begin{bmatrix}
a_{i_2, j_2} & a_{i_2, j_3} \\
a_{i_3, j_2} & a_{i_3, j_3} \\
\end{bmatrix}
$$

마이너에 $(-1)^{i+j}$를 곱한 값을 코팩터(cofactor, 여인수) $C_{i,j}$라고 한다. 코팩터를 사용하여 위 식을 다시 표현 하면 아래와 같다.<br>
즉 $(-1)^{i+j}$의 $i+j$ 값이 짝수 이면 **코팩터**는 양수<br>
$(-1)^{i+j}$의 $i+j$ 값이 홀수 이면 **코팩터**는 음수라는 의미<br>
<br>
* 왜 마이너값에 를 $(-1)^{i+j}$ 연산하여 계산할까?<br>
* 이미지 분석할 때 차원축소를 하는 방법과 어떻게 다른가?

$$
(-1)^{i+j_0} M_{i,j_0} =  C_{i,j_0}
$$

$$
def(A) = \sum_{i=1}^N C_{i,j_0} a_{i,j_0} = \sum_{j=1}^N C_{i_0, j} a_{i_0,j}
$$

예)

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
$$

임의 행 또는 열을 선택<br>
<br>
만약 <span style="color:red">첫번째 열</span>을 선택했을시 이 행렬의 행렬식은 아래와 같다<br>


$$
det(A) = \left\{ (-1)^{1 + 1} M_{1, 1} \right\} a_{1, 1} + \left\{ (-1)^{2 + 1} M_{2, 1} \right\} a_{2, 1} + \left\{ (-1)^{3 + 1} M_{3, 1} \right\} a_{3, 1}
$$

$$
= M_{1, 1} a_{1, 1} + -M_{2, 1} a_{2, 1} + M_{3, 1} a_{3, 1}
$$

$$
= M_{1,1} \times 1 + M_{2, 1} \times 4 + M_{3, 1} \times 7
$$

$M_{1,1}$은 기존의 행렬에서 1번째 행과 열을 지워서 만들어진 행렬의 식.
$$
M_{1, 1} = 
\left( \begin{bmatrix} 
5 & 6 \\
8 & 9 \\
\end{bmatrix}\right)
$$



$M_{2, 1}$은 기존의 행렬에서 2번째 행과 1번재 열을 지워서 만든 행렬의 식.

$$
M_{2, 1} = \left( \begin{bmatrix} 2 & 3 \\
8 & 9 \\
\end{bmatrix}
\right)
$$

$M_{3,1}$은 기존의 행렬에서 3번째 행과 1번째 열을 지워서 만든 행렬의 식.

$$
M_{3, 1} = \left( 
\begin{bmatrix}
2 & 3 \\
5 & 6 \\
\end{bmatrix}
\right)
$$

$M_{1, 1}, M_{2, 1}, M_{3, 1}$은 코팩터 공식을 이용하여 계산이 가능.<br> 
이렇게 재귀적으로 계산 하다 보면 행렬식은 결국 스칼라 값에 도달하게 된다.<br>
스칼라의 행렬식은 자기 자신으로 정의.

$$
def \left( \begin{bmatrix} a \end{bmatrix} \right) = a
$$

위의 정의를 사용하면 크기가 2, 3인 정방 행렬의 행렬식은 다음과 같아진다.

* 2 $\times$ 2 행렬의 행렬식


$$ def \left( \begin{bmatrix} a & b \\ c & d \\ \end{bmatrix} \right) = \left\{ (-1)^{1 + 1} M_{1 , 1} \right\} a + \left\{ (-1)^{2 + 1} M_{2, 1} \right\} c$$

$$
= \left\{
M_{1,1} \times a + (-M_{2, 1}) \times c
\right\}
$$
$$
= d \times a - b \times c
$$

$$
def \left( \begin{bmatrix} a & b \\ c & d \end{bmatrix} \right) = ad - bc
$$

* 3 $\times$ 3 행렬의 행렬식

$$
def \left( 
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix}
\right)
=
\left\{(-1)^{1 + 1} M_{1, 1} \right\} a + \left\{ (-1)^{2 + 1} M_{2, 1}\right\} d + \left\{ (-1)^{3 + 1} M_{3, 1} \right\} g
$$

$$
= M_{1, 1} \times a + (-M_{2, 1}) \times d + M_{3, 1} \times g 
$$

$$
= \left\{ (-1)^{1 + 1} M_{1,1} \right\} e \times a + \left\{ (-1)^{2 + 1} M_{2, 1} \right\} h \times a -\left( \left\{ (-1)^{1 + 1} M_{1, 1} \right\} b \times d  + \left\{ (-1)^{2 + 1} M_{2, 1} \right\} h \times d \right) +  \left\{ (-1)^{1 + 1} M_{1, 1} \right\} b \times g + \left\{ (-1)^{2 + 1} M_{2, 1} \right\} e \times g 
$$

$$
= iea - fha - (ibd - chd) + fbg - ceg
$$

$$
def \left( 
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix}
\right)
= aei + bfg + cdh - ceg - bdi - afh
$$

행렬식의 값도 대각합과 마찬가지로 0이나 음수가 될 수 있다.<br>
Numpy에서는 linalg 서브패키지의 <span style="color:red">det</span>명령으로 행렬식을 계산할 수 있다.

In [4]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
np.linalg.det(A)

-2.0000000000000004

In [6]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.linalg.det(B)

-9.5161973539299405e-16

행렬식은 다음과 같은 성질을 만족한다.
* 전치 행렬의 행렬식은 원래의 행렬의 행렬식과 같다.

$$
def(A^T) = def(A)
$$

* 단위 행렬의 행렬식은 1이다.

$$
def(I) = 1
$$

* 두 행렬의 곱의 행렬식은 각 행렬의 행렬식의 곱과 같다.

$$
def(AB) = def(A) def(B)
$$

* 역행렬의 행렬식은 원래 행렬의 행렬식의 역수와 같다.

$$
def(A^{-1}) = \frac {1}{def(A)}
$$

### 부호와 크기의 관계

행렬의 양-정부호 성질과 대각합/행렬식은 다음과 같은 관계가 있다. 역은 일반적으로 성립하지 않는다.
* 행렬의 양-정부호(positive-definite)이면 대각합이 양수이다.
* 행렬의 양-정부호(positive-definite)이면 행렬식이 양수이다.
* 행렬의 양-준정부호(positive-semidefinite)이면 행렬식은 0이다.

### 연습 문제 5
다음 행렬의 대각합과 행렬식을 구하고 위의 관계가 성립하는지 확인한다.

$$
A = 
\begin{bmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2 \\
\end{bmatrix}
$$

In [14]:
import numpy as np

A = np.array([[2, -1 , 0], [-1, 2, -1], [0, -1, 2]])
A

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [19]:
x = np.array([1, 2, 3])
x_ = np.array([-1, -2, -3])

In [20]:
np.dot(np.dot(x.T, A), x)

12

In [22]:
# 양-정부호
np.dot(np.dot(x_.T, A), x_)

12

$$
B = 
\begin{bmatrix}
1 & 1 \\
1 & 1 \\
\end{bmatrix}
$$

In [24]:
B = np.array([[1, 1], [1, 1]])
B

array([[1, 1],
       [1, 1]])

In [26]:
b = np.array([2, 1])
b_ = np.array([-2, 1])

In [28]:
np.dot(np.dot(b.T, B), b)

9

In [29]:
# 양-정부호
np.dot(np.dot(b_.T, B), b_)

1

$$
C = 
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
$$