# 벡터와 행렬의 연산

벡터, 행렬도 사칙연산이 가능.<br> 
행렬 연산을 이용하면 대량의 데이터를 간단한 수식으로 표현가능.<br>
그러나 행렬 연산은 기존의 숫자 사칙연산과는 몇 가지가 다른 점이 있으므로 차이점에 주의.<br>
<br>
### **벡터와 행렬의 덧셈과 뺄셈**
<br>
같은 크기를 가진 두 벡터나 행렬은 덧셈과 뺄셈이 가능.<br>
연산은 같은 위치에 있는 원소끼리 덧샘과 뺄셈을 하면된다. 이러한 연산을 요소별(element-wise) 연산이라 한다.<br>
<br>
$$
x = 
\begin{bmatrix}
10 \\
11 \\
12 \\
13 \\
14 \\
\end{bmatrix}
$$

$$
y = 
\begin{bmatrix}
0 \\
1 \\
2 \\
3 \\
4 \\
\end{bmatrix}
$$

벡터 $x$와$y$의 $x$+$y$과 $x$-$y$

$$
x + y =
\begin{bmatrix}
10 \\
11 \\
12 \\
13 \\
14 \\
\end{bmatrix}
\;
+
\;
\begin{bmatrix}
0 \\
1 \\
2 \\
3 \\
4 \\
\end{bmatrix}
\;
=
\;
\begin{bmatrix}
10 + 0 \\
11 + 1 \\
12 + 2 \\
13 + 3 \\
14 + 4 \\
\end{bmatrix}
\;
=
\;
\begin{bmatrix}
10 \\
12 \\
14 \\
16 \\
18 \\
\end{bmatrix}
$$

$$
x - y =
\begin{bmatrix}
10 \\
11 \\
12 \\
13 \\
14 \\
\end{bmatrix}
\;
-
\;
\begin{bmatrix}
0 \\
1 \\
2 \\
3 \\
4 \\
\end{bmatrix}
\;
=
\;
\begin{bmatrix}
10 - 0 \\
11 - 1 \\
12 - 2 \\
13 - 3 \\
14 - 4 \\
\end{bmatrix}
\;
=
\;
\begin{bmatrix}
10 \\
10 \\
10 \\
10 \\
10 \\
\end{bmatrix}
$$

Numpy로 계산하면 다음과 같다.

In [3]:
import numpy as np

x = np.array([10, 11, 12, 13, 14])
x

array([10, 11, 12, 13, 14])

In [5]:
y = np.array([0, 1, 2, 3, 4])
y

array([0, 1, 2, 3, 4])

In [6]:
x + y

array([10, 12, 14, 16, 18])

In [7]:
x - y

array([10, 10, 10, 10, 10])

행렬도 마찬가지로 덧셈, 뺄셈 가능

$$
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
\;
+
\;
\begin{bmatrix}
10 & 12 \\
13 & 14 \\
\end{bmatrix}
\;
-
\;
\begin{bmatrix}
1 & 4 \\
6 & 8 \\
\end{bmatrix}
\;
=
\;
\begin{bmatrix}
10 & 10 \\
10 & 10 \\
\end{bmatrix}
$$

In [11]:
np.array([[1,2], [3,4]]) + np.array([[10,12], [13, 14]]) - np.array([[1, 4], [6, 8]])

array([[10, 10],
       [10, 10]])

### **스칼라와 벡터/행렬의 곱셈**
<br>
스칼라 값 $c$를 곱하는 것은 벡터 $x$또는 행렬 $A$의 모든 원소에 $c$를 곱하는 것과 같다.
<br>

$$
\color{red}c \times
\begin{bmatrix}
x_1 \\
x_2 \\
\end{bmatrix}
\;
=
\;
\begin{bmatrix}
\color{red}cx_1 \\
\color{red}cx_2 \\
\end{bmatrix}
$$

$$
\color{red}c \times
\begin{bmatrix}
a_{1, 1} & a_{1, 2} \\
a_{2, 1} & a_{2, 2} \\
\end{bmatrix}
\;
=
\;
\begin{bmatrix}
\color{red}ca_{1, 1} & \color{red}ca_{1, 2} \\
\color{red}ca_{2, 1} & \color{red}ca_{2, 2} \\
\end{bmatrix}
$$

### **선형 조합**

벡터/행렬에 다음처럼 스칼라 값을 곱한뒤 빼거나 더한것을 **선형 조합(linear combination)** 이라고 한다.<br>
$$
c_{1}x_{1} + c_{2}x_{2} +\cdots +c_{L}x_{L}
$$
벡터나 행렬을 선형조합해도 크기는 변하지 않는다.<br>
$$ c_1, c_2, \ldots, c_L \in \mathbf{R} $$
$$ x_1, x_2, \ldots, x_L, x \in \mathbf{R}^M $$
$$ A_1, A_2, \ldots, A_L, A \in \mathbf{R}^{ M \times N }$$

### **벡터와 벡터의 곱셈** 
<br>
벡터를 곱셈하는 방법은 **내적(inner product)**과 **외적(outer product)** 등 여러 가지가 있다.<br> 
여기서는 내적만 다룰것. 그러므로 그냥 내적을 곱셈으로 칭한다.<br>
내적은 점(dot)으로 표기하는 경우도 있기에 dot product라고 하기도한다.<br>
$$
x \cdot y = x^T y
$$

벡터 곱셈을 하려면 만족해야 할 조건이 있다.

1. 두 벡터의 길이가 같아야 한다.
2. 앞의 벡터가 행 벡터이고 뒤 벡터가 열 벡터여야 한다.<br>
<br>
이때 두 벡터의 곱은 다음처럼 정의<br>
<br>

$$
x^T y =
\begin{bmatrix}
x_1 & x_2 & \ldots & x_N
\end{bmatrix}
\begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_N \\
\end{bmatrix}
= x_1 y_1 + \cdots + x_N y_N
= \sum_{i=1}^N x_i y_i
$$

각각의 크기를 표시하면 다음과 같다.

$$
x \in \mathbf{R}^{N \times 1}, y \in \mathbf{R}^{N \times 1} \rightarrow x^T y \in \mathbf{R}
$$

이렇게 전치연산을 하며 곱셈을 하는 이유는?
실제 데이터 분석을 할때 이렇게 사용하는 경우가 많기 때문이다.

### **가중합**
<br>
**가중합(weighted sum)**이란 복수의 데이터를 단순히 합하는 것이 아니다. 각각의 수에 가중치를 곱한후 이 곱셈들을 다시 합한것. 이것을 **선형조합(linear combination)**이라 한다.<br>
<br>
만약 <span style="color:red">데이터</span>와 <span style="color:blue">가중치</span>가 아래와 같으면
<br>
$$
\color{red}x = \begin{bmatrix} x_1, \ldots, x_N \end{bmatrix}^{T}, 
\color{blue}w = \begin{bmatrix} w_1, \ldots, w_N \end{bmatrix}^{T}
$$
<br>
가중합은 다음과 같다.<br>
$$
\color{blue}w^T \color{red}x = \begin{bmatrix} w_1 & w_2 & \ldots & w_N \end{bmatrix} 
\begin{bmatrix} 
x_1 \\ 
x_2 \\ 
\vdots \\
x_N
\end{bmatrix}
=
\sum_{i=1}^N \color{blue}w^T \color{red}x
$$
<br>
or
<br>
$$
\color{red}x^T \color{blue}w = \begin{bmatrix} x_1 & x_2 & \ldots & x_N \end{bmatrix} 
\begin{bmatrix} 
w_1 \\ 
w_2 \\ 
\vdots \\
w_N
\end{bmatrix}
=
\sum_{i=1}^N \color{red}x^T \color{blue}w
$$

벡터 곱셈의 예
$$
x =
\begin{bmatrix}
10 \\
9 \\
8 \\
\end{bmatrix}
, \;\;
y =
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
$$

$$
x^T y =
\begin{bmatrix}
10 & 9 & 8
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
=
10 \cdot 1 + 9 \cdot 2 + 8 \cdot 3 = 52
$$

이를 Numpy로 계산<br> 
주의점 Numpy에서는 스칼라 값이 아닌 행렬로 추출된다.

In [15]:
x = np.array([[10], [9], [8]])
y = np.array([[1], [2], [3]])
np.dot(x.T, y)[0, 0] # 행렬로 표시되기 때문에 스칼라 값만 추출

52

Numpy에서는 1차원 배열끼리 곱할 수 있으며, 전치연산을 하지 않아도 앞 벡터는 행, 뒤 벡터는 열로 가정하고 계산

In [17]:
x = np.array([10, 9, 8])
y = np.array([1, 2, 3])
np.dot(x, y)

52